### PR TITLE
Upgrade some examples to SDK 0.17

### PR DESCRIPTION
**Pull request by vkarpov15**
## What was changed

Upgraded a bunch of examples to SDK v0.17. Doesn't look like any changes are required, but I spot checked the steps in the README for each example and found one issue with signals-queries

## Why?

samples should use latest version of the SDK unless they're explicitly demonstrating using an older SDK version

## Checklist

1. Closes 

2. How was this tested:

Walked through README steps for each sample with 0.17.x

3. Any docs updates needed?

### CODE REVIEW

**Review by bergundy — APPROVED** [review]
Thanks, we should upgrade all of the samples

**Comment by vkarpov15** [comment]
@bergundy I upgraded and verified the remaining samples, except for the monorepo-folders issue that I ran into #85

**Comment by bergundy** [comment]
@vkarpov15 please fix the build so we can merge.

**Comment by vkarpov15** [comment]
@bergundy I fixed the build in this branch and `main`. Should be good to go. Only issue is that monorepo-folders isn't upgraded yet pending #86

**Pull request merged**
